classdef TabPiece < handle
% TabPiece UI container for displaying and interacting with a single piece.
%
%   This class defines the layout and controls for a tab dedicated to one
%   piece within the application. It manages image preview, 
%   piece metadata, and action buttons (e.g., subpixel detection,
%   filtering, error calculation).
%
%   Properties:
%       - gridLayoutTab: main grid layout container for the tab 
%       - gridLayoutPieceInfo: grid layout for displaying piece information 
%       - gridLayoutButtons: grid layout for arranging action buttons 
%       - idPiece: Id of the Bbox of the piece
%       - previewPiece: UI component for showing the piece image 
%       - imagePiece: Image of the piece
%       - showImageButton: button to show the piece image 
%       - detectedEdgesButton: button to display subpixel edge detection 
%       - filterButton: button to display edges filtered
%       - errorButton: button to display error metrics 
    
    properties
        tabPiece matlab.ui.container.Tab
        gridLayoutTab matlab.ui.container.GridLayout
        scrollPanel
        vbox
        
        idPiece string;
        previewPiece matlab.ui.control.UIAxes
        imagePiece uint8 = uint8([]);

        showImageButton 
        detectedEdgesButton 
        filterButton 
        errorButton 
        prevFilterStage 
        nextFilterStage 
        showFilterStages 
        prevErrorStage 
        nextErrorStage 
        showErrorStages
    end
    
    methods (Access = public)
        
        function self = TabPiece(resultsConsole, image, id, title)
            
            self.idPiece = id;
            self.imagePiece = image;
            self.tabPiece = uitab(resultsConsole, 'Title', title);
            self.tabPiece.UserData = self;
            
            self.buildLayoutTab(image);
            self.buildFirstRow();
            self.buildSecondRow();
            self.buildThirdRow();
            self.buildFourthRow();
            
            set(self.vbox, 'Heights', [40 40 40 40]);
            self.scrollPanel.Heights = 200;
        end


        function id = getId(self)
            id = self.idPiece;
        end


        function setShowImageButtonAction(self, callbackFcn)
            self.showImageButton.ButtonPushedFcn = callbackFcn;
        end


        function setShowDetectedEdgesAction(self, callbackFcn)
            self.detectedEdgesButton.ButtonPushedFcn = callbackFcn;
        end


        function setShowFilteredEdgesAction(self, callbackFcn)
            self.filterButton.ButtonPushedFcn = callbackFcn;
        end


        function setShowErrorOnSVGAction(self, callbackFcn)
            self.errorButton.ButtonPushedFcn = callbackFcn;
        end


        function setShowFilteredStagesAction(self, callbackFcn)
            self.showFilterStages.ButtonPushedFcn = callbackFcn;
        end


        function setShowPreviousFilteredStageAction(self, callbackFcn)
            self.prevFilterStage.ButtonPushedFcn = callbackFcn;
        end


        function setShowNextFilteredStageAction(self, callbackFcn)
            self.nextFilterStage.ButtonPushedFcn = callbackFcn;
        end


        function setShowErrorStagesAction(self, callbackFcn)
            self.showErrorStages.ButtonPushedFcn = callbackFcn;
        end

        
        function setShowPreviousErrorStageAction(self, callbackFcn)
            self.prevErrorStage.ButtonPushedFcn = callbackFcn;
        end


        function setShowNextErrorStageAction(self, callbackFcn)
            self.nextErrorStage.ButtonPushedFcn = callbackFcn;
        end

    end

    methods (Access = private)
        
        function buildLayoutTab(self, image)
            % TabLayout
            self.gridLayoutTab = uigridlayout(self.tabPiece, [1, 2]);
            self.gridLayoutTab.RowHeight = {'1x'};
            self.gridLayoutTab.ColumnWidth = {'1x', '1x'};
            self.gridLayoutTab.ColumnSpacing = 8;
            self.gridLayoutTab.Padding = [5 5 5 5];
            self.gridLayoutTab.BackgroundColor = [1 1 1];
        
            % PreviewImage
            self.previewPiece = uiaxes(self.gridLayoutTab);
            self.previewPiece.Layout.Row = 1;
            self.previewPiece.Layout.Column = 1;
            self.previewPiece.Toolbar.Visible = 'off';
            self.previewPiece.Interactions = [];
            imshow(image, 'Parent', self.previewPiece);
            axis(self.previewPiece, 'image');
            axis(self.previewPiece, 'off');
        
            % scroollPanel
            self.scrollPanel = uix.ScrollingPanel('Parent', self.gridLayoutTab, ...
                'BackgroundColor', [1 1 1]);
            self.scrollPanel.Layout.Row = 1;
            self.scrollPanel.Layout.Column = 2;
        
            % verticalBox
            self.vbox = uix.VBox('Parent', self.scrollPanel, ...
                'Spacing', 10, 'Padding', 10, ...
                'BackgroundColor', [1 1 1]);
        end


        function buildFirstRow(self)
            hbox1 = uix.HBox('Parent', self.vbox, ...
                'Spacing', 8, 'BackgroundColor', [1 1 1]);

            self.showImageButton = uibutton(hbox1, 'push', ...
                'Text', 'Mostrar imagen', ...
                'FontName', 'Segoe UI', ...
                'FontSize', 13, ...
                'BackgroundColor', [0.20 0.35 0.65], ...
                'FontColor', [1 1 1], ...
                'Tooltip', 'Muestra la imagen original', ...
                'FontWeight', 'bold', ...
                'WordWrap', 'on');
            
            self.detectedEdgesButton = uibutton(hbox1, 'push', ...
                'Text', 'Mostrar bordes detectados', ...
                'FontName', 'Segoe UI', ...
                'FontSize', 13, ...
                'BackgroundColor', [0.20 0.35 0.65], ...
                'FontColor', [1 1 1], ...
                'Tooltip', 'Muestra los bordes detectados', ...
                'FontWeight', 'bold', ...
                'WordWrap', 'on');
            
            set(hbox1, 'Widths', [-1 -1]); 
        end


        function buildSecondRow(self)
            hbox2 = uix.HBox('Parent', self.vbox, 'Spacing', ...
                8, 'BackgroundColor', [1 1 1]);

            self.filterButton = uibutton(hbox2, 'push', ...
                'Text', 'Mostrar bordes filtrados', ...
                'FontName', 'Segoe UI', ...
                'FontSize', 13, ...
                'BackgroundColor', [0.20 0.35 0.65], ...
                'FontColor', [1 1 1], ...
                'Tooltip', 'Muestra los bordes filtrados', ...
                'FontWeight', 'bold', ...
                'WordWrap', 'on');
        
            self.errorButton = uibutton(hbox2, 'push', ...
                'Text', 'Mostrar error producido', ...
                'FontName', 'Segoe UI', ...
                'FontSize', 13, ...
                'BackgroundColor', [0.20 0.35 0.65], ...
                'FontColor', [1 1 1], ...
                'Tooltip', 'Muestra la comparación con el modelo SVG y el error calculado', ...
                'FontWeight', 'bold', ...
                'WordWrap', 'on');

            set(hbox2, 'Widths', [-1 -1]);
        end


        function buildThirdRow(self)
            hbox3 = uix.HBox('Parent', self.vbox, ...
                'Spacing', 8, 'BackgroundColor', [1 1 1]);

            self.prevFilterStage = uibutton(hbox3, 'push', ...
                'Text', 'Etapa previa', ...
                'FontName', 'Segoe UI', ...
                'FontSize', 11, ...
                'BackgroundColor', [0.94 0.94 0.94], ...
                'FontWeight', 'normal', ...
                'FontColor', [0.25 0.25 0.25], ...
                'Tooltip', 'Muestra la etapa de filtrado anterior', ...
                'WordWrap', 'on');

            self.showFilterStages = uibutton(hbox3, 'push', ...
                'Text', 'Mostrar etapas de filtrado', ...
                'FontName', 'Segoe UI', ...
                'FontSize', 11, ...
                'BackgroundColor', [0.94 0.94 0.94], ...
                'FontWeight', 'normal', ...
                'FontColor', [0.25 0.25 0.25], ...
                'Tooltip', 'Visualiza todas las etapas del proceso de filtrado', ...
                'WordWrap', 'on');

            self.nextFilterStage = uibutton(hbox3, 'push', ...
                'Text', 'Etapa posterior', ...
                'FontName', 'Segoe UI', ...
                'FontSize', 11, ...
                'BackgroundColor', [0.94 0.94 0.94], ...
                'FontWeight', 'normal', ...
                'FontColor', [0.25 0.25 0.25], ...
                'Tooltip', 'Avanza a la siguiente etapa de filtrado', ...
                'WordWrap', 'on');

            set(hbox3, 'Widths', [-1 -1 -1]);
        end


        function buildFourthRow(self)
            hbox4 = uix.HBox('Parent', self.vbox, ...
                'Spacing', 8, 'BackgroundColor', [1 1 1]);

            self.prevErrorStage = uibutton(hbox4, 'push', ...
                'Text', 'Etapa previa', ...
                'FontName', 'Segoe UI', ...
                'FontSize', 11, ...
                'BackgroundColor', [0.94 0.94 0.94], ...
                'FontWeight', 'normal', ...
                'FontColor', [0.25 0.25 0.25], ...
                'Tooltip', 'Muestra la etapa de error anterior', ...
                'WordWrap', 'on');
            
            self.showErrorStages = uibutton(hbox4, 'push', ...
                'Text', 'Mostrar etapas de error', ...
                'FontName', 'Segoe UI', ...
                'FontSize', 11, ...
                'BackgroundColor', [0.94 0.94 0.94], ...
                'FontWeight', 'normal', ...
                'FontColor', [0.25 0.25 0.25], ...
                'Tooltip', 'Visualiza todas las etapas intermedias del cálculo de error', ...
                'WordWrap', 'on');
            
            self.nextErrorStage = uibutton(hbox4, 'push', ...
                'Text', 'Etapa posterior', ...
                'FontName', 'Segoe UI', ...
                'FontSize', 11, ...
                'BackgroundColor', [0.94 0.94 0.94], ...
                'FontWeight', 'normal', ...
                'FontColor', [0.25 0.25 0.25], ...
                'Tooltip', 'Avanza a la siguiente etapa del análisis de error', ...
                'WordWrap', 'on');

            set(hbox4, 'Widths', [-1 -1 -1]);
        end

    end

end

