function [clusters, noisePoints] = analyzeSubstructuresWithDBSCAN(edges, epsilon, minPts)
% ANALYZESUBSTRUCTURESWITHDBSCAN Aplica DBSCAN a los puntos subpíxel para detectar agrupaciones internas.
%
%   Entrada:
%     - edges: estructura con campos .x y .y
%     - epsilon: radio de vecindad para DBSCAN (en píxeles)
%     - minPts: número mínimo de puntos para formar un cluster
%
%   Salida:
%     - clusters: celda de estructuras con mismos campos que edges por grupo
%     - noisePoints: estructura con puntos detectados como ruido

    x = edges.x(:);
    y = edges.y(:);
    
    labels = dbscan([x y], epsilon, minPts);
    numClusters = max(labels);

    clusters = cell(1, numClusters);
    for i = 1:numClusters
        mask = labels == i;
        clusters{i} = struct( ...
            'x', edges.x(mask), ...
            'y', edges.y(mask), ...
            'nx', edges.nx(mask), ...
            'ny', edges.ny(mask), ...
            'curv', edges.curv(mask), ...
            'i0', edges.i0(mask), ...
            'i1', edges.i1(mask) ...
        );
    end

    % Ruido (label == -1)
    noiseMask = labels == -1;
    noisePoints = struct( ...
        'x', edges.x(noiseMask), ...
        'y', edges.y(noiseMask), ...
        'nx', edges.nx(noiseMask), ...
        'ny', edges.ny(noiseMask), ...
        'curv', edges.curv(noiseMask), ...
        'i0', edges.i0(noiseMask), ...
        'i1', edges.i1(noiseMask) ...
    );
end
